### ISSUE TITLE
reproduce tool: AttributeError in manual run mode

### ISSUE THREAD

**Issue by fuzzah** [gardatech/bugbane#19]
```
Traceback (most recent call last):
  File "/usr/local/bin/bb-reproduce", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/bugbane/tools/reproduce/main.py", line 164, in main
    bug_samples_dir = os.path.join(args.suite, "bug_samples")
AttributeError: 'Namespace' object has no attribute 'suite'
```

Also it's better to save reproduce results ASAP, not after saving bug samples.

**Comment by fuzzah** [comment]
fixed
