### ISSUE TITLE
build tool: TypeError in main.py on python<3.8

### ISSUE THREAD

**Issue by fuzzah** [gardatech/bugbane#20]
```
Traceback (most recent call last):
  File "/usr/bin/bb-build", line 33, in <module>
    sys.exit(load_entry_point('bugbane', 'console_scripts', 'bb-build')())
  File "/bugbane/bugbane/tools/builder/main.py", line 50, in main
    log.verbose3("Loaded vars: %s", pprint.pformat(bane_vars, sort_dicts=False))
TypeError: pformat() got an unexpected keyword argument 'sort_dicts'
```

`sort_dicts` parameter is available starting from Python 3.8
Could be detected earlier with proper use of tox :(

**Comment by fuzzah** [comment]
merged to main
