### ISSUE TITLE
reproduce tool: AttributeError if crash causes hang

### ISSUE THREAD

**Issue by fuzzah** [gardatech/bugbane#21]
This may happen in some weirdo apps that take forever to run:
```
[*] BugBane reproduce tool
Reproducing with env vars: {'UBSAN_OPTIONS': 'print_stacktrace=1:allocator_may_return_null=1', 'ASAN_OPTIONS': 'allocator_may_return_null=1', 'LANG': 'C', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'}
Checking spec 'AFL++:./out ./basic/app:app01 ./basic/app:app02 ./basic/app:app03 ./basic/app:app04 ./basic/app:app05 ./basic/app:app06 ./basic/app:app07 ./basic/app:app08 ./basic/app:app09 ./basic/app:app10 ./basic/app:app11 ./basic/app:app12 ./basic/app:app13 ./basic/app:app14 ./basic/app:app15 ./asan/app:app16'...
Checking path ./out (AFL++)
Will search for crashes and hangs in directory 'app01' for app './basic/app'
Sample masks: './out/app01/crashes/id*' (crashes) and './out/app01/hangs/id*' (hangs)
Will search for crashes and hangs in directory 'app02' for app './basic/app'
Sample masks: './out/app02/crashes/id*' (crashes) and './out/app02/hangs/id*' (hangs)
Traceback (most recent call last):
  File "/usr/bin/bb-reproduce", line 33, in <module>
    sys.exit(load_entry_point('bugbane', 'console_scripts', 'bb-reproduce')())
  File "/bugbane/bugbane/tools/reproduce/main.py", line 161, in main
    results = harvester.collect_fuzzing_results()
  File "/bugbane/bugbane/tools/reproduce/harvester.py", line 122, in collect_fuzzing_results
    self.collect_one_spec_fuzzing_results(fuzzer_type, sync_dir, build_specs)
  File "/bugbane/bugbane/tools/reproduce/harvester.py", line 170, in collect_one_spec_fuzzing_results
    binary_path, crashes_path_mask, hangs_path_mask
  File "/bugbane/bugbane/tools/reproduce/reproducers/default_reproducer.py", line 48, in run_binary_on_samples
    cards.extend(self.run_binary_on_crashes(binary_path, crashes_mask))
  File "/bugbane/bugbane/tools/reproduce/reproducers/default_reproducer.py", line 59, in run_binary_on_crashes
    card = self.run(cmd, binary_path, sample, self.one_run_try)
  File "/bugbane/bugbane/tools/reproduce/reproducers/default_reproducer.py", line 100, in run
    verdict, output = run_method(cmd, self.run_env)
  File "/bugbane/bugbane/tools/reproduce/reproducers/default_reproducer.py", line 120, in one_run_try
    output = output.decode(errors="replace")
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by fuzzah** [comment]
resolved
